### PR TITLE
added support for redshift clusters using SSL

### PR DESCRIPTION
**Pull request by Gauravshah**

### CODE REVIEW

**Comment by IanMeyers** [comment]
This is great, but we'll also need this option added to addClusterEndpoint.js. Happy to merge once it's there as well!

**Comment by Gauravshah** [comment]
@IanMeyers done. Thanks

**Comment by Gauravshah** [comment]
not sure if I should open a new pull, or reopening this pull will get back new commits

**Comment by Gauravshah** [comment]
@IanMeyers do you want me to open a new pull request for this one ?

**Comment by IanMeyers** [comment]
Yes please!

**Pull request closed without merging**
