### PR TITLE
suffix support and load cluster failure message

### PR DESCRIPTION
**Pull request by bmasciarelli**
*Description of changes:*
I've included support for using filenameFilter parameter as suffix for S3 notification. This allows to have more than one Lambda trigger with same prefix. It also reduces unnecesary function calls.
This was made to support an specific use case, I know there's work to do to make it work generally but I'm not that into js. If you can point me what's missing I can try to round it up.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by IanMeyers** [comment]
Thanks for your contribution. I'm curious though why/if the filenameFilterRegex option didn't work for you?

**Comment by bmasciarelli** [comment]
To be honest I didn't realize I could use something like (file1|file2).

Despite that, all files I need to process are or will be under same prefix, so I would need to use a single event source in lambda with every file listed in the regex.

I think that the suffix solution is easier to mantain and it also saves executions as far as I understand.

Regards

**Comment by IanMeyers** [comment]
Can you elaborate a bit about what the structure of the files are in the prefix? We may be able to support this right away.

**Comment by bmasciarelli** [comment]
Sure, it's somethig like:

- bucket root
-- myprefix
--- file_to_process_1
---- folder
----- file_to_process_2
----- other many files I don't want to process
---- folder2
----- more many other files I don't want to process
-- other_prefix

**Comment by IanMeyers** [comment]
Do you know the 'file_to_process_*' values ahead of time?

**Comment by bmasciarelli** [comment]
Yes, both content and name

**Comment by IanMeyers** [comment]
So these can be setup currently just with separate configurations for each of the input prefixes you want to track, and also using filenameFilterRegex for suffixes. Is that an option for you?

**Pull request closed without merging**
