### PR TITLE
added ability to replace rows based on few column values

### PR DESCRIPTION
**Pull request by Gauravshah**
This would help if we are constantly overwriting data for a table

### CODE REVIEW

**Comment by IanMeyers** [comment]
This is quite cool. However, I see that the configuration of primary columns for overwrite is done on a per-cluster basis. This doesn't sit well with me. I think it would be very confusing if you are issuing the same copy command to multiple clusters, but using different criteria to merge data. I'd request that for right now, this be a configuration wide setting that is applied to all clusters being loaded.

**Comment by Gauravshah** [comment]
sure makes sense, will update in couple of days.

**Comment by IanMeyers** [comment]
Also, I wonder if you could use this same functionality to add support for table Append: http://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE_APPEND.html? Both require a mirrored table structure, but in the Append case we don't need the primary keys, and instead of DELETE/INSERT we'd issue an APPEND statement. Thoughts?

**Comment by Gauravshah** [comment]
append would not work for this scenario since the rows would not be identical completely. Only the primary columns would be the same.

**Comment by Gauravshah** [comment]
does `dynamoConfig.Item.replaceRows` & `dynamoConfig.Item.primaryColumns` sound correct place to put in the configuration ?

**Comment by Gauravshah** [comment]
also it would not sound correct if truncate is cluster level option `dynamoConfig.Item.loadClusters.L[0].M.truncateTarget` but the replace rows being global

**Comment by Gauravshah** [comment]
@IanMeyers any thoughts on this ?

**Pull request closed without merging**
